project:
  type: book

book:
  title: "heavy_quarks"
  author: "Marco Garofalo"
  date: today
  chapters:
    - index.qmd
    - cB211.072.64_PRACE.qmd
    - cB211.072.64_inclusive.qmd
    - cB211.072.64_HLT.qmd
    - cross_check_cB211.072.64_th6_t48_64.qmd
    - checks_sigma_extrapolation.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - scratch_area.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    #html-math-method: mathjax
    # include-in-header: mathjax.html
    html-math-method: katex
    # html-math-method: webtex
    # html-math-method:
    #   method: mathjax
    #   url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
      
    
  #pdf:
  #  documentclass: scrreprt



