project:
  type: book

book:
  title: "Meson_masses_clover"
  author: "Marco Garofalo"
  date: today
  chapters:
    - index.qmd
    - cB211.072.64_masses.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    # html-math-method: mathjax
    html-math-method: katex
    # include-in-header: mathjax.html
  #pdf:
  #  documentclass: scrreprt



