project:
  type: book

book:
  title: "heavy_quarks"
  author: "Marco Garofalo"
  date: today
  chapters:
    - index.qmd
    - masses.qmd
    - cB211.072.48_dGamma.qmd
    - cB211.072.64_PRACE.qmd
    # - cB211.072.64_inclusive.qmd
    # - cB211.072.64_HLT.qmd
    - cB211.072.64_dGamma.qmd
    - cB211.072.64_bounding.qmd
    - cB211.072.96_dGamma.qmd
    - cD211.054.96_dGamma.qmd
    - cC211.06.80_dGamma.qmd
    - cE211.044.112_dGamma.qmd
    - stability.qmd
    - overview_dGamma.qmd
    - continuum_limit_dGamma.qmd
    # - cross_check_cB211.072.64_th6_t48_64.qmd
    # - checks_sigma_extrapolation.qmd
    # - check_Emax.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - volume.qmd
    - scratch_area.qmd

bibliography: references.bib

format:
  html:
    theme: default
    grid:
      sidebar-width: 250px
      body-width:    900px
      margin-width:  250px
      gutter-width:	 1.5em
    max-width: 2000px
    margin: 0
    #html-math-method: mathjax
    # include-in-header: mathjax.html
    html-math-method: katex
    # html-math-method: webtex
    # html-math-method:
    #   method: mathjax
    #   url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    resources: 
    - shinylive-sw.js
filters:
  - shinylive
  #pdf:
  #  documentclass: scrreprt



