#  cB211.072.64 disc vs con


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
require(tikzDevice)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x, y)) +
    geom_point()
  assign("ggp", plotly::ggplotly(gg), envir = parent.frame())
  # ggp
  df # NOT returning a plot
}
res1 <- f1(df)
ggp # Let knit handle the plot
myplotly(ggplot())
```



```{r,results='asis', echo=FALSE}
dir <- "/home/garofalo/analysis/heavy_quarks/data_Inc/out/"
ths <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "9.5", "2.0", "4.0")
# ths <- c( "2.0", "4.0")
thsd <- c("1", "2")
howmany <- (length(ths) + length(thsd))
dG <- rep(0, howmany)
dG_err <- rep(0, howmany)
q2 <- rep(0, howmany)
label <- rep(0, howmany)
count <- 1
for (i in seq_along(ths)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  dG[count] <- fit[1, 1]
  dG_err[count] <- fit[1, 2]
  q2[count] <- fit[1, 3]
  label[count] <- " sum-con"
  count <- count + 1
  #####
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z0-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z0-con"
  # count <- count + 1
  # #####
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z1-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z1-con"
  # count <- count + 1
  # #####
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z2-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z2-con"
  # count <- count + 1
}
for (i in seq_along(thsd)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  dG[count] <- fit[1, 1]
  dG_err[count] <- fit[1, 2]
  q2[count] <- fit[1, 3]
  label[count] <- " sum-dis"
  count <- count + 1
  #####
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th",thsd[i],"_t48_r-r.dat_fit_HLT_Z0-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z0-disc"
  # count <- count + 1
  #
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th",thsd[i],"_t48_r-r.dat_fit_HLT_Z1-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z1-disc"
  # count <- count + 1
  #
  # P <- read_fit_P_file(paste0(dir, "cB211.072.64_th",thsd[i],"_t48_r-r.dat_fit_HLT_Z2-sigma4_fit_P.dat"))
  # dG[count] <- P$P[1, 2]
  # dG_err[count] <- P$P[1, 3]
  # q2[count] <- fit[1, 3]
  # label[count] <- "Z2-disc"
  # count <- count + 1
}
gg <- myggplot(fill = FALSE)
gg <- gg + geom_pointrange(aes(
  x = q2, y = dG,
  ymin = dG - dG_err, ymax = dG + dG_err, color = label,
  shape = label
))

fig <- myplotly(gg, "", "$q^2[GeV]$", "$24 \\pi^3 d\\Gamma/dq^2 [GeV^-3]$", to_print = TRUE)
```

```{r,results='asis', echo=FALSE}
dir <- "/home/garofalo/analysis/heavy_quarks/data_Inc/out/"
ths <- c("2.0", "4.0")
# ths <- c( "2.0", "4.0")
thsd <- c("1", "2")
howmany <- (length(ths))
dG <- rep(0, howmany)
dG_err <- rep(0, howmany)
q2 <- rep(0, howmany)
dG_disc <- rep(0, howmany)
dG_err_disc <- rep(0, howmany)
q2_disc <- rep(0, howmany)

label <- rep(0, howmany)
count <- 1
for (i in seq_along(ths)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  dG[count] <- fit[1, 1]
  dG_err[count] <- fit[1, 2]
  q2[count] <- fit[1, 3]
  label[count] <- " sum-con"
  count <- count + 1
}
count <- 1
for (i in seq_along(thsd)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  dG_disc[count] <- fit[1, 1]
  dG_err_disc[count] <- fit[1, 2]
  q2_disc[count] <- fit[1, 3]
  label[count] <- " sum-dis"
  count <- count + 1
}
dG_err <- dG_err_disc / dG + dG_disc * dG_err / (dG^2)
dG <- dG_disc / dG
# gg <- myggplot(fill = FALSE)
# gg <- gg + geom_pointrange(aes(
#   x = q2, y = dG,
#   ymin = dG - dG_err, ymax = dG + dG_err, color = label,
#   shape = label
# ))

cat("ratio disc/con (q^2=", q2[1], " ) = ", mean_print(dG[1], dG_err[1]), "\n\n")
cat("ratio disc/con (q^2=", q2[2], " ) = ", mean_print(dG[2], dG_err[2]), "\n\n")
dG_err <- dG_err / (dG^2)
dG <- 1 / dG
cat("ratio con/disc (q^2=", q2[1], " ) = ", mean_print(dG[1], dG_err[1]), "\n\n")
cat("ratio con/disc (q^2=", q2[2], " ) = ", mean_print(dG[2], dG_err[2]), "\n")

# fig <- myplotly(gg, "", "$q^2[GeV]$", "ratio con/disc", to_print = TRUE)
```

### Separate the contributions

```{r,results='asis', echo=FALSE}
dir <- "/home/garofalo/analysis/heavy_quarks/data_Inc/out/"
ths <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "9.5", "2.0", "4.0")
# ths <- c( "2.0", "4.0")
thsd <- c("1", "2")
howmany <- (length(ths) + length(thsd)) * 3
dG <- rep(0, howmany)
dG_err <- rep(0, howmany)
q2 <- rep(0, howmany)
label <- rep(0, howmany)
count <- 1
for (i in seq_along(ths)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  # dG[count] <- fit[1, 1]
  # dG_err[count] <- fit[1, 2]
  # q2[count] <- fit[1, 3]
  # label[count] <- " sum-con"
  # count <- count + 1
  #####
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z0-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z0-con"
  count <- count + 1
  # #####
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z1-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z1-con"
  count <- count + 1
  # #####
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_Z2-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z2-con"
  count <- count + 1
}
for (i in seq_along(thsd)) {
  mt <- read_df(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_output"))
  all_obs <- get_all_corr(mt)
  ########
  fit <- get_full_res("dGammadq_GEV3_sigma4", all_obs, mt)
  # dG[count] <- fit[1, 1]
  # dG_err[count] <- fit[1, 2]
  # q2[count] <- fit[1, 3]
  # label[count] <- " sum-dis"
  # count <- count + 1
  #####
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_fit_HLT_Z0-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z0-disc"
  count <- count + 1
  #
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_fit_HLT_Z1-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z1-disc"
  count <- count + 1
  #
  P <- read_fit_P_file(paste0(dir, "cB211.072.64_th", thsd[i], "_t48_r-r.dat_fit_HLT_Z2-sigma4_fit_P.dat"))
  dG[count] <- P$P[1, 2]
  dG_err[count] <- P$P[1, 3]
  q2[count] <- fit[1, 3]
  label[count] <- "Z2-disc"
  count <- count + 1
}
gg <- myggplot(fill = FALSE)
gg <- gg + geom_pointrange(aes(
  x = q2, y = dG,
  ymin = dG - dG_err, ymax = dG + dG_err, color = label,
  shape = label
))

fig <- myplotly(gg, "", "$q^2[GeV]$", "$24 \\pi^3 d\\Gamma/dq^2 [GeV^-3]$", to_print = TRUE)
```

<!-- debugging -->

<!-- ```{r} -->
<!-- df <- NULL -->
<!-- file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th4.0_t48_36_cs.dat_output") -->
<!-- mt <- read_df(file) -->
<!-- all_obs <- get_all_corr(mt) -->
<!-- df <- add_corr_to_df( -->
<!--   string = paste0("Z_{0}"), -->
<!--   all_obs = all_obs, mt = mt, df = df, -->
<!--   log = FALSE, number = NULL, nudge = 0, -->
<!--   print_res = FALSE, logx = 0, -->
<!--   rename = "Z_0 4.0" -->
<!-- ) -->
<!-- file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2.0_t48_36_cs.dat_output") -->
<!-- mt <- read_df(file) -->
<!-- all_obs <- get_all_corr(mt) -->
<!-- df <- add_corr_to_df( -->
<!--   string = paste0("Z_{0}"), -->
<!--   all_obs = all_obs, mt = mt, df = df, -->
<!--   log = FALSE, number = NULL, nudge = 0, -->
<!--   print_res = FALSE, logx = 0, -->
<!--   rename = "Z_0 2.0" -->
<!-- ) -->

<!-- file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th5_t48_36_cs.dat_output") -->
<!-- mt <- read_df(file) -->
<!-- all_obs <- get_all_corr(mt) -->
<!-- df <- add_corr_to_df( -->
<!--   string = paste0("Z_{0}"), -->
<!--   all_obs = all_obs, mt = mt, df = df, -->
<!--   log = FALSE, number = NULL, nudge = 0, -->
<!--   print_res = FALSE, logx = 0, -->
<!--   rename = "Z_0 5" -->
<!-- ) -->

<!-- file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th6_t48_36_cs.dat_output") -->
<!-- mt <- read_df(file) -->
<!-- all_obs <- get_all_corr(mt) -->
<!-- df <- add_corr_to_df( -->
<!--   string = paste0("Z_{0}"), -->
<!--   all_obs = all_obs, mt = mt, df = df, -->
<!--   log = FALSE, number = NULL, nudge = 0, -->
<!--   print_res = FALSE, logx = 0, -->
<!--   rename = "Z_0 6" -->
<!-- ) -->


<!-- gg <- plot_df_corr_ggplot(df, noribbon = TRUE) -->
<!-- gg <- gg + scale_y_continuous(trans = "log10") -->
<!-- fig <- myplotly(gg, "", "t", "m_eff", to_print = TRUE) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- Z<-"Z0" -->
<!-- df<-NULL -->
<!-- mt1<-read_df(paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th5_t48_36_cs.dat_HLT_kernel")) -->
<!-- all_obs<- get_all_corr(mt1) -->

<!-- df1<-add_corr_to_df( -->
<!--   string=paste0("HLT_",Z,"-sig0.005000-alpha2.00_lam1024"), -->
<!--                     all_obs=all_obs,mt=mt1,df = NULL, -->
<!--                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE) -->

<!-- tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit,  -->
<!--                  "label"=paste0(df1$label,"-th5")) -->

<!-- df<-rbind(df,tmp) -->

<!-- mt1<-read_df(paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th4.0_t48_36_cs.dat_HLT_kernel")) -->
<!-- all_obs<- get_all_corr(mt1) -->

<!-- df1<-add_corr_to_df( -->
<!--   string=paste0("HLT_",Z,"-sig0.005000-alpha2.00_lam1024"), -->
<!--                     all_obs=all_obs,mt=mt1,df = NULL, -->
<!--                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE) -->

<!-- tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit,  -->
<!--                  "label"=paste0(df1$label,"-th4.0")) -->

<!-- df<-rbind(df,tmp) -->

<!-- mt1<-read_df(paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th6_t48_36_cs.dat_HLT_kernel")) -->
<!-- all_obs<- get_all_corr(mt1) -->

<!-- df1<-add_corr_to_df( -->
<!--   string=paste0("HLT_",Z,"-sig0.005000-alpha2.00_lam1024"), -->
<!--                     all_obs=all_obs,mt=mt1,df = NULL, -->
<!--                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE) -->

<!-- tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit,  -->
<!--                  "label"=paste0(df1$label,"-th6")) -->

<!-- df<-rbind(df,tmp) -->

<!-- ################ plot -->

<!-- gg<-myggplot(shape = FALSE,fill = FALSE) -->
<!-- gg<-gg + geom_line(aes(x=df$omega  , y=df$Kb, -->
<!--                        color=paste0("K-",df$label) -->
<!--                        ),linetype="dashed" ) -->
<!-- gg<-gg + geom_line(aes(x=df$omega  , y=df$K, -->
<!--                        color=paste0("exact-",df$label)), linetype="solid") -->


<!-- # gg<-gg + geom_line(aes(x=df$omega  , y=df$K-df$Kb, -->
<!-- #                        color=paste0("diff-",df$label) -->
<!-- #                        ),linetype="dotted") -->
<!-- fig<- myplotly(gg,"","omega", "K", to_print=TRUE , legend_position = c(0.5,0.95),legend_title = "") -->
<!-- ``` -->

## effective mass Y $\theta=2\pi$

```{r, echo=FALSE, results='asis', warning=FALSE}
df <- NULL
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th1_t48_r-r.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("M_{Ds}_ss"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "M_Ds"
)
df <- add_corr_to_df(
  string = paste0("M_Y_2"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} disc "
)

######## connected
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2.0_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)


df <- add_corr_to_df(
  string = paste0("M_Y_2"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "M_Y_{2} conn"
)


#########################################################################################################

file1 <- paste0("/home/garofalo/analysis/pi0/data/B64/out/B64.dat_output")
mt11 <- read_df(file1)
all_obs1 <- get_all_corr(mt11)
#
#
df <- add_corr_to_df(
  string = "M_{piTM}",
  all_obs = all_obs1, mt = mt11, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0, rename = "M_Pi+_TM"
)
df <- add_corr_to_df(
  string = "M_{pi0}_full_sub_vev",
  all_obs = all_obs1, mt = mt11, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0, rename = "M_Pi0"
)
l <- which(grepl("M_Pi", df$label))
df$y[l] <- sqrt(df$y[l]^2 + (2 * pi / 64)^2)
df$fit[l] <- sqrt(df$fit[l]^2 + (2 * pi / 64)^2)
#

gg <- plot_df_corr_ggplot(df, noribbon = TRUE)
# gg <- gg + scale_y_continuous(trans = "log10")
fig <- myplotly(gg, "", "t", "m_eff", to_print = TRUE)
```

## th=2 correlators

```{r, echo=FALSE, results='asis', warning=FALSE}
df <- NULL
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th1_t48_r-r.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

file1 <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2.0_t48_36_cs.dat_output")
mt1 <- read_df(file1)
all_obs1 <- get_all_corr(mt1)

for (Y in c("Y_{1}", "Y_{2}", "Y_{3}", "Y_{4}", "Y_{5}")) {
  df <- NULL
  ######
  df <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs, mt = mt, df = df,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0,
    rename = paste(Y, " disc ")
  )
  df_disc <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs, mt = mt, df = NULL,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0, reshape = FALSE
  )

  #
  ######## connected



  df <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs1, mt = mt1, df = df,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0,
    rename = paste(Y, " con ")
  )
  df_con <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs1, mt = mt1, df = NULL,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0, reshape = FALSE
  )

  #
  #
  # #########################################################################################################
  #
  # file1 <- paste0("/home/garofalo/analysis/pi0/data/B64/out/B64.dat_output")
  # mt11 <- read_df(file1)
  # all_obs1 <- get_all_corr(mt11)
  # #
  # #
  # df <- add_corr_to_df(
  #   string = "M_{piTM}",
  #   all_obs = all_obs1, mt = mt11, df = df,
  #   log = FALSE, number = NULL, nudge = 0,
  #   print_res = FALSE, logx = 0, rename = "M_Pi+_TM"
  # )
  # df <- add_corr_to_df(
  #   string = "M_{pi0}_full_sub_vev",
  #   all_obs = all_obs1, mt = mt11, df = df,
  #   log = FALSE, number = NULL, nudge = 0,
  #   print_res = FALSE, logx = 0, rename = "M_Pi0"
  # )
  # l <- which(grepl("M_Pi", df$label))
  # df$y[l] <- sqrt(df$y[l]^2 + (2 * pi / 64)^2)
  # df$fit[l] <- sqrt(df$fit[l]^2 + (2 * pi / 64)^2)
  # #
  dfp <- data.frame("t" = df_con$x, "y" = df_con$y, "err" = df_con$err, "y1" = df_disc$y, "y1e" = df_disc$err)
  names(dfp) <- c(
    "t", paste0(Y, "_con"), paste0("d", Y, "_con"),
    paste0(Y, "_disc"), paste0("d", Y, "_disc")
  )
  write.table(dfp, file = paste0("data_", Y, "_th2.0.txt"), row.names = FALSE)
  gg <- plot_df_corr_ggplot(df, noribbon = TRUE)
  # gg <- gg + scale_y_continuous(trans = "log10")
  fig <- myplotly(gg, "", "t", "", to_print = TRUE)
}
```




## th=4 correlators

```{r, echo=FALSE, results='asis', warning=FALSE}
df <- NULL
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2_t48_r-r.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

file1 <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th4.0_t48_36_cs.dat_output")
mt1 <- read_df(file1)
all_obs1 <- get_all_corr(mt1)

for (Y in c("Y_{1}", "Y_{2}", "Y_{3}", "Y_{4}", "Y_{5}")) {
  df <- NULL
  ######
  df <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs, mt = mt, df = df,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0,
    rename = paste(Y, " disc ")
  )
  df_disc <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs, mt = mt, df = NULL,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0, reshape = FALSE
  )

  #
  ######## connected



  df <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs1, mt = mt1, df = df,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0,
    rename = paste(Y, " con ")
  )
  df_con <- add_corr_to_df(
    string = paste0(Y),
    all_obs = all_obs1, mt = mt1, df = NULL,
    log = FALSE, number = NULL, nudge = 0,
    print_res = FALSE, logx = 0, reshape = FALSE
  )

  #
  #
  # #########################################################################################################
  #
  # file1 <- paste0("/home/garofalo/analysis/pi0/data/B64/out/B64.dat_output")
  # mt11 <- read_df(file1)
  # all_obs1 <- get_all_corr(mt11)
  # #
  # #
  # df <- add_corr_to_df(
  #   string = "M_{piTM}",
  #   all_obs = all_obs1, mt = mt11, df = df,
  #   log = FALSE, number = NULL, nudge = 0,
  #   print_res = FALSE, logx = 0, rename = "M_Pi+_TM"
  # )
  # df <- add_corr_to_df(
  #   string = "M_{pi0}_full_sub_vev",
  #   all_obs = all_obs1, mt = mt11, df = df,
  #   log = FALSE, number = NULL, nudge = 0,
  #   print_res = FALSE, logx = 0, rename = "M_Pi0"
  # )
  # l <- which(grepl("M_Pi", df$label))
  # df$y[l] <- sqrt(df$y[l]^2 + (2 * pi / 64)^2)
  # df$fit[l] <- sqrt(df$fit[l]^2 + (2 * pi / 64)^2)
  # #
  dfp <- data.frame("t" = df_con$x, "y" = df_con$y, "err" = df_con$err, "y1" = df_disc$y, "y1e" = df_disc$err)
  names(dfp) <- c(
    "t", paste0(Y, "_con"), paste0("d", Y, "_con"),
    paste0(Y, "_disc"), paste0("d", Y, "_disc")
  )
  write.table(dfp, file = paste0("data_", Y, "_th4.0.txt"), row.names = FALSE)
  gg <- plot_df_corr_ggplot(df, noribbon = TRUE)
  # gg <- gg + scale_y_continuous(trans = "log10")
  fig <- myplotly(gg, "", "t", "", to_print = TRUE)
}
```


```{r,  echo=FALSE, results='asis'}
df <- NULL
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2.0_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("Z_{2}"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} conn 2.0"
)

file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th4.0_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("Z_{2}"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} conn 4.0"
)

file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th5_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("Z_{2}"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} conn 5"
)
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th6_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("Z_{2}"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} conn 6"
)

gg <- plot_df_corr_ggplot(df, noribbon = TRUE)
gg <- gg + scale_y_continuous(trans = "log10")
fig <- myplotly(gg, "", "t", "m_eff", to_print = TRUE)
```


## effective mass Y $\theta=4\pi$

```{r, echo=FALSE, results='asis', warning=FALSE}
df <- NULL
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2_t48_r-r.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)

df <- add_corr_to_df(
  string = paste0("M_{Ds}_ss"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "M_Ds"
)
df <- add_corr_to_df(
  string = paste0("M_Y_2"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "Y_{2} disc "
)

######## connected
file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th4.0_t48_36_cs.dat_output")
mt <- read_df(file)
all_obs <- get_all_corr(mt)


df <- add_corr_to_df(
  string = paste0("M_Y_2"),
  all_obs = all_obs, mt = mt, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0,
  rename = "M_Y_{2} conn"
)

#########################################################################################################

file1 <- paste0("/home/garofalo/analysis/pi0/data/B64/out/B64.dat_output")
mt11 <- read_df(file1)
all_obs1 <- get_all_corr(mt11)
#
#
df <- add_corr_to_df(
  string = "M_{piTM}",
  all_obs = all_obs1, mt = mt11, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0, rename = "M_Pi+_TM"
)
df <- add_corr_to_df(
  string = "M_{pi0}_full_sub_vev",
  all_obs = all_obs1, mt = mt11, df = df,
  log = FALSE, number = NULL, nudge = 0,
  print_res = FALSE, logx = 0, rename = "M_Pi0"
)
l <- which(grepl("M_Pi", df$label))
df$y[l] <- sqrt(df$y[l]^2 + (4 * pi / 64)^2)
df$fit[l] <- sqrt(df$fit[l]^2 + (4 * pi / 64)^2)
#

gg <- plot_df_corr_ggplot(df, noribbon = TRUE)
# gg <- gg + scale_y_continuous(trans = "log10")
fig <- myplotly(gg, "", "t", "m_eff", to_print = TRUE)
```


## Stability

::: {.panel-tabset}

```{r, echo=FALSE, results='asis', warning=FALSE}
Zs <- c("Z0", "Z1", "Z2")
ths <- c("2.0", "4.0")
thsd <- c("1", "2")
for (Z in Zs) {
  cat("\n## ", Z, "\n\n")
  for (i in seq_along(ths)) {
    cat("\n###  $\\theta=$", ths[i], "  $p=\\theta\\pi/L$\n\n")
    s <- "0.130000"
    s <- "0.070000"
    fileA <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", ths[i], "_t48_36_cs.dat_HLT_AoverB")
    mtA <- read_df(fileA)
    all_obsA <- get_all_corr(mtA)
    dfA <- NULL
    dfA <- get_block(
      string = paste0("HLT_", Z, "-sig", s, "-alpha0.00"),
      all_obs = all_obsA, mt = mtA, df = dfA,
      log = FALSE, number = NULL, nudge = 0,
      print_res = FALSE, logx = 10, ix = 11,
      iy = 6, ierr = 7, ifit = 9, ierrfit = 10,
      iplateau = 1,
      rename = paste0("HLT_", Z, "-sig", s, "-alpha0.00-th", ths[i])
    )

    fileA <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", thsd[i], "_t48_r-r.dat_HLT_AoverB")
    mtA <- read_df(fileA)
    all_obsA <- get_all_corr(mtA)
    dfA <- get_block(
      string = paste0("HLT_", Z, "-sig", s, "-alpha0.00"),
      all_obs = all_obsA, mt = mtA, df = dfA,
      log = FALSE, number = NULL, nudge = 0,
      print_res = FALSE, logx = 10, ix = 11,
      iy = 6, ierr = 7, ifit = 9, ierrfit = 10,
      iplateau = 1,
      rename = paste0("HLT_", Z, "-sig", s, "-alpha0.00-th", thsd[i], "-disc")
    )
    ######## printing for alessandro
    fileA <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", ths[i], "_t48_36_cs.dat_HLT_AoverB")
    mtA <- read_df(fileA)
    all_obsA <- get_all_corr(mtA)
    dfA_con <- get_block(
      string = paste0("HLT_", Z, "-sig", s, "-alpha0.00"),
      all_obs = all_obsA, mt = mtA, df = NULL,
      log = FALSE, number = NULL, nudge = 0,
      print_res = FALSE, logx = 0, ix = 11,
      iy = 6, ierr = 7, ifit = 9, ierrfit = 10,
      iplateau = 1,
      rename = paste0("HLT_", Z, "-sig", s, "-alpha0.00-th", ths[i])
    )

    fileA <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", thsd[i], "_t48_r-r.dat_HLT_AoverB")
    mtA <- read_df(fileA)
    all_obsA <- get_all_corr(mtA)
    dfA_disc <- get_block(
      string = paste0("HLT_", Z, "-sig", s, "-alpha0.00"),
      all_obs = all_obsA, mt = mtA, df = NULL,
      log = FALSE, number = NULL, nudge = 0,
      print_res = FALSE, logx = 0, ix = 11,
      iy = 6, ierr = 7, ifit = 9, ierrfit = 10,
      iplateau = 1,
      rename = paste0("HLT_", Z, "-sig", s, "-alpha0.00-th", thsd[i], "-disc")
    )
    lrow <- length(dfA_con[1, ])
    for (j in c((length(dfA_con[, 1]) + 1):length(dfA_disc[, 1]))) {
      dfA_con[j, ] <- rep(NA, lrow)
    }
    dfp <- data.frame(
      "A_con" = dfA_con$x, "A0_ref_con" = dfA_con[, 12], "Z_con" = dfA_con$y, "dZ_con" = dfA_con$err,
      "A_disc" = dfA_disc$x, "A0_ref_disc" = dfA_disc[, 12], "Z_disc" = dfA_disc$y, "dZ_dis" = dfA_disc$err
    )
    write.table(dfp, file = paste0("data_rho", Z, "_s", s, "_alpha0.00_th", ths[i], ".txt"), row.names = FALSE)

    #####


    dfA$x <- dfA$x - log10(dfA[, 12]) # A/A0_ref
    dfA$xfit <- dfA$xfit - log10(dfA[, 12]) # A/A0_ref
    dfA$tmin <- dfA$tmin - log10(dfA[, 12]) # A/A0_ref
    dfA$tmax <- dfA$tmax - log10(dfA[, 12]) # A/A0_ref
    gg <- plot_df_corr_ggplot(dfA, width = 0.01, stroke = 1, alpha = 0.2, size_error = 0.6)

    avep <- (max(dfA$fit) + min(dfA$fit)) / 2.0
    sdp <- max(dfA$fit + dfA$errfit) - min(dfA$fit - dfA$errfit)
    fig <- myplotly(gg, paste0("rho-", Z), "log10(A/A0)_ref", "",
      to_print = TRUE,
      output = "HTML", to_webgl = FALSE,
      # yrange=c(avep-2*sdp,avep+2*sdp),
      legend_position = c(0.2, 1)
    )
  }
}
```

:::



::: {.panel-tabset}


```{r, echo=FALSE, results='asis', warning=FALSE}
Zs <- c("Z0", "Z1", "Z2")
ths <- c("2.0", "4.0")
thsd <- c("1", "2")
for (Z in Zs) {
  cat("\n## ", Z, "\n\n")
  for (i in seq_along(ths)) {
    cat("\n###  $\\theta=$", ths[i], "  $p=\\theta\\pi/L$\n\n")

    file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", ths[i], "_t48_36_cs.dat_fit_HLT_", Z, "-sigma4")
    gg <- plot_fit(file, "sigma", "conn", width = 0.002)

    # file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th5_t48_36_cs.dat_fit_HLT_", Z, "-sigma4")
    # gg <- plot_fit(file, "sigma", "conn5", width = 0.002,gg)


    file <- paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th", thsd[i], "_t48_r-r.dat_fit_HLT_", Z, "-sigma4")
    gg <- plot_fit(file, "sigma", "disc", width = 0.002, gg)

    fig <- myplotly(gg, title, "$\\sigma$", paste0(Z, "-th", ths[i]),
      to_print = TRUE, output = "HTML", legend_position = c(0.8, 0.9),
      legend_title = "alpha"
    )
  }
}
```

:::




## reconstruction 

::: {.panel-tabset}



```{r, echo=FALSE, results='asis', warning=FALSE, eval=FALSE}

Zs<- c("Z0","Z1","Z2")
for (Z in Zs){
cat("\n## ",Z,"\n\n")
 
  
df<-NULL
s<-"0.070000"
###################### Con
mt1<-read_df(paste0("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th2.0_t48_36_cs.dat_HLT_kernel"))
all_obs<- get_all_corr(mt1)

df1<-add_corr_to_df(
  string=paste0("HLT_",Z,"-sig",s,"-alpha0.00_lam1024"),
                    all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)


tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit, 
                 "label"=paste0(df1$label,"-th-",2.0,"con")
                )

df<-rbind(df,tmp)
###################### disc
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_th1_t48_r-r.dat_HLT_kernel")
all_obs<- get_all_corr(mt1)

df1<-add_corr_to_df(
  string=paste0("HLT_",Z,"-sig",s,"-alpha0.00_lam1024"),
                    all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)


tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit, 
                 "label"=paste0(df1$label,"-th-",2.0,"disc")
                )

df<-rbind(df,tmp)


################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=df$omega  , y=df$Kb,
                       color=paste0("K-",df$label)
                       ),linetype="dashed" )
gg<-gg + geom_line(aes(x=df$omega  , y=df$K,
                       color=paste0("exact")), linetype="solid")


# gg<-gg + geom_line(aes(x=df$omega  , y=df$K-df$Kb,
#                        color=paste0("diff-",df$label)
#                        ),linetype="dotted")
fig<- myplotly(gg,"","omega", "K", to_print=TRUE , legend_position = c(0.5,0.95),legend_title = "")
}

```


:::