# cross check cB211.072.64 th6 t48-64

```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
require(tikzDevice)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
myplotly(ggplot())
```

## Effective mass $D_s$


```{r, echo=FALSE, results='asis', warning=FALSE}
mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output")
all_obs<- get_all_corr(mt)


df<-add_corr_to_df(string = "M_{Ds}_ss",all_obs=all_obs,mt=mt,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = TRUE)

######################################################à

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputY/Y.log")
dfY<- get_block_n(Ylog,5)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,2],
                "y"=dfY[,5],
                "err"=dfY[,6],
                "xfit"=dfY[,2],
                "fit"=dfY[,7],
                "errfit"=dfY[,8],
                "label"="meff_hlt",
                "tmin"=tmin,
                "tmax"=tmax
                )
df<-rbind(df,tmp)


gg<- plot_df_corr_ggplot(df)

fig<- myplotly(gg,"","t", "$M_{eff}$", to_print=TRUE )
```


#  Y


```{r, echo=FALSE, results='asis', warning=FALSE}


df<-add_corr_to_df(string = "Y_{1}",all_obs=all_obs,mt=mt,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Y_{2}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Y_{3}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Y_{4}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Y_{5}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)

######################################################

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputY/Y.dat")
##############################
dfY<- get_block_n(Ylog,1)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Y1_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,1.5)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Y2_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,2)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Y3_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,2.5)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Y4_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,3)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Y5_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################



gg<- plot_df_corr_ggplot(df, noribbon = TRUE)

fig<- myplotly(gg,"","t", "$Y$", to_print=TRUE )
```





#  Z


```{r, echo=FALSE, results='asis', warning=FALSE}


df<-add_corr_to_df(string = "Z_{0}",all_obs=all_obs,mt=mt,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Z_{1}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df<-add_corr_to_df(string = "Z_{2}",all_obs=all_obs,mt=mt,df = df,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)

######################################################

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/Z.dat")
##############################
dfY<- get_block_n(Ylog,1)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Z0_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,1.5)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Z1_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,2)
list<-which(dfY[,7]!=0)
tmin<- dfY[list[1],2]
tmax<- dfY[list[length(list)],2][]
tmp<-data.frame("x"=dfY[,6], "y"=dfY[,7], "err"=dfY[,8], "xfit"=dfY[,2],
                "fit"=dfY[,7], "errfit"=dfY[,8], "label"="Z2_hlt",
                "tmin"=tmin, "tmax"=tmax          )
df<-rbind(df,tmp)
##############################

df$err<-df$err/df$y
df$y<-log(df$y)

gg<- plot_df_corr_ggplot(df, noribbon = TRUE)

fig<- myplotly(gg,"","t", "$\\ln(Z)$", to_print=TRUE )
```





#  Z0 reconstruction

<!-- ## Jack vs Boot -->


<!-- ```{r, echo=FALSE, results='asis', warning=FALSE} -->

<!-- df<-NULL -->

<!-- ###################### MG -->
<!-- mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_AoverB") -->
<!-- dfY<- get_block_n(mt,1) -->
<!-- #dfY<- rbind(dfY, get_block_n(mt,2)) -->

<!-- mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output") -->
<!-- all_obs<- get_all_corr(mt1) -->
<!-- df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha2.00", all_obs=all_obs,mt=mt1,df = NULL, -->
<!--                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE,  -->
<!--                    ,rename="MG-Z0-alpha2.0") -->

<!-- # df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha1", all_obs=all_obs,mt=mt1,df = df1, -->
<!-- #                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE, rename="MG-Z0-alpha1") -->

<!-- tmp<-data.frame("lam"=dfY[,1], "A/A0"=dfY[,2]/dfY[,4], "B/Bnorm"=dfY[,3], "rho"=df1$y, -->
<!--                 "drho"=df1$err, -->
<!--                   "label"=paste0(df1$label,"jack") -->
<!--                 ) -->
<!-- df<-rbind(df,tmp) -->
<!-- ##################################################################à -->
<!-- # boot -->
<!-- ##################################################################à -->
<!-- mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_AoverB_boot") -->
<!-- dfY<- get_block_n(mt,1) -->
<!-- #dfY<- rbind(dfY, get_block_n(mt,2)) -->

<!-- mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output_boot") -->
<!-- all_obs<- get_all_corr(mt1) -->
<!-- df1<-add_corr_to_df(string ="HLT_Z0-alpha0", all_obs=all_obs,mt=mt1,df = NULL, -->
<!--                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE,  -->
<!--                    ,rename="MG-Z0-alpha0") -->

<!-- # df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha1", all_obs=all_obs,mt=mt1,df = df1, -->
<!-- #                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE, rename="MG-Z0-alpha1") -->

<!-- tmp<-data.frame("lam"=dfY[,1], "A/A0"=dfY[,2]/dfY[,4], "B/Bnorm"=dfY[,3], "rho"=df1$y, -->
<!--                 "drho"=df1$err, -->
<!--                   "label"=paste0(df1$label,"boot") -->
<!--                 ) -->
<!-- df<-rbind(df,tmp) -->

<!-- ################ plot -->
<!-- gg<-myggplot(shape = FALSE,fill = FALSE) -->
<!-- gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,2], -->
<!--                        color=paste0("A/A0-",df$label), -->
<!--                        linetype=paste0("A/A0-",df$label))) -->
<!-- fig<- myplotly(gg,"","lam", "A/A0", to_print=TRUE , -->
<!--                # yrange=c(0,0.0001), xrange=c(-25,0) -->
<!--                ) -->
<!-- ################ plot -->
<!-- gg<-myggplot(shape = FALSE,fill = FALSE) -->
<!-- gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,3], -->
<!--                        color=paste0("B/Bnorm-",df$label), -->
<!--                        linetype=paste0("B/Bnorm-",df$label))) -->
<!-- fig<- myplotly(gg,"","lam", "B/Bnorm", to_print=TRUE, -->
<!--                # yrange=c(0,20), xrange=c(-25,0)  -->
<!--                ) -->
<!-- ################ plot -->
<!-- df1$x<- log2(df1$x) -->
<!-- df1$xfit<- log2(df1$xfit) -->
<!-- df1$tmin<-log2(df1$tmin) -->
<!-- df1$tmax<-log2(df1$tmax) -->
<!-- gg<- plot_df_corr_ggplot(df1) -->
<!-- #gg<-myggplot(fill = FALSE,shape = FALSE) -->
<!-- gg<-gg + geom_point(aes(x=log2(df$lam)  , y=df[,4], -->
<!--                        color=paste0("rho-",df$label) -->
<!--                        )) -->
<!-- gg<-gg + geom_errorbar(aes(x=log2(df$lam)  , ymin=df[,4]-df[,5], -->
<!--                            ymax=df[,4]+df[,5], -->
<!--                        color=paste0("rho-",df$label) -->
<!--                        )) -->



<!-- fig<- myplotly(gg,"","log2(lam)", "rho", to_print=TRUE ) -->

<!-- ``` -->

## MG vs NT

```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_0_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,13.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z0-alpha0"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z0-alpha1"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z0-alpha2"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_AoverB")
dfY<- get_block_n(mt,1)
dfY<- rbind(dfY, get_block_n(mt,2))
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z0-sig0.120000-alpha2.00", all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, 
                   ,rename="MG-Z0-alpha0")

df1<-add_corr_to_df(string ="HLT_Z0-sig0.120000-alpha0.00", all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, rename="MG-Z0-alpha1")


######
################ plot
df1$x<- log2(df1$x)
df1$xfit<- log2(df1$xfit)
df1$tmin<-log2(df1$tmin)
df1$tmax<-log2(df1$tmax)
gg<- plot_df_corr_ggplot(df1)
#gg<-myggplot(fill = FALSE,shape = FALSE)
gg<-gg + geom_point(aes(x=log2(df$lam)  , y=df[,4],
                       color=paste0("rho-",df$label)
                       ))
gg<-gg + geom_errorbar(aes(x=log2(df$lam)  , ymin=df[,4]-df[,5],
                           ymax=df[,4]+df[,5],
                       color=paste0("rho-",df$label)
                       ))



fig<- myplotly(gg,"","log2(lam)", "rho", to_print=TRUE )
#############


tmp<-data.frame("lam"=dfY[,1], "A/A0"=dfY[,2]/dfY[,4], "B/Bnorm"=dfY[,3], "rho"=df1$y,
                "drho"=df1$err,
                  "label"=df1$label
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,2],
                       color=paste0("A/A0-",df$label),
                       linetype=paste0("A/A0-",df$label)))
fig<- myplotly(gg,"","lam", "A/A0", to_print=TRUE ,
               # yrange=c(0,0.0001), xrange=c(-25,0)
               )
################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,3],
                       color=paste0("B/Bnorm-",df$label),
                       linetype=paste0("B/Bnorm-",df$label)))
fig<- myplotly(gg,"","lam", "B/Bnorm", to_print=TRUE,
               # yrange=c(0,20), xrange=c(-25,0) 
               )


```



```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_0_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,18)
tmp<-data.frame("omega"=dfY[,3], "K"=dfY[,4], "Kb"=dfY[,5], 
                 "label"="NT-Z0-alpha1"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_kernel")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z0-sig0.120000-alpha0.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z0-sig0.120000-alpha0.00_lam32.0000",  
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z0-sig0.120000-alpha2.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
# res<- get_res(string ="HLT_Z0-sig0.120-alpha1_lam16384.0000",all_obs=all_obs,mt1)
# df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha1-E0o2_lam16384.0000", all_obs=all_obs,mt=mt1,df = df1,
#                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE)


tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit, 
                 "label"=paste0(df1$label)
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=df$omega  , y=df$Kb,
                       color=paste0("K-",df$label),
                       linetype=paste0("K-",df$label)))
gg<-gg + geom_line(aes(x=df$omega  , y=df$K,
                       color="exact",
                       linetype="exact"))

fig<- myplotly(gg,"","omega", "K", to_print=TRUE )


```


#  Z1 reconstruction

## MG vs NT


```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_1_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,13.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z1-alpha0"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z1-alpha1"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z1-alpha2"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_AoverB")
dfY<- get_block_n(mt,1)
dfY<- rbind(dfY, get_block_n(mt,2))
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z1-sig0.120000-alpha2.00", all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, 
                   ,rename="MG-Z1-alpha0")

df1<-add_corr_to_df(string ="HLT_Z1-sig0.120000-alpha0.00", all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, rename="MG-Z1-alpha1")


######
################ plot
df1$x<- log2(df1$x)
df1$xfit<- log2(df1$xfit)
df1$tmin<-log2(df1$tmin)
df1$tmax<-log2(df1$tmax)
gg<- plot_df_corr_ggplot(df1)
#gg<-myggplot(fill = FALSE,shape = FALSE)
gg<-gg + geom_point(aes(x=log2(df$lam)  , y=df[,4],
                       color=paste0("rho-",df$label)
                       ))
gg<-gg + geom_errorbar(aes(x=log2(df$lam)  , ymin=df[,4]-df[,5],
                           ymax=df[,4]+df[,5],
                       color=paste0("rho-",df$label)
                       ))



fig<- myplotly(gg,"","log2(lam)", "rho", to_print=TRUE )
#############


tmp<-data.frame("lam"=dfY[,1], "A/A0"=dfY[,2]/dfY[,4], "B/Bnorm"=dfY[,3], "rho"=df1$y,
                "drho"=df1$err,
                  "label"=df1$label
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,2],
                       color=paste0("A/A0-",df$label),
                       linetype=paste0("A/A0-",df$label)))
fig<- myplotly(gg,"","lam", "A/A0", to_print=TRUE ,
               # yrange=c(0,0.0001), xrange=c(-25,0)
               )
################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,3],
                       color=paste0("B/Bnorm-",df$label),
                       linetype=paste0("B/Bnorm-",df$label)))
fig<- myplotly(gg,"","lam", "B/Bnorm", to_print=TRUE,
               # yrange=c(0,20), xrange=c(-25,0) 
               )


```

```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_1_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,18)
tmp<-data.frame("omega"=dfY[,3], "K"=dfY[,4], "Kb"=dfY[,5],
                 "label"="NT-Z0-alpha1"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_kernel")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z1-sig0.120000-alpha0.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z1-sig0.120000-alpha0.00_lam32.0000",
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z1-sig0.120000-alpha2.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
# res<- get_res(string ="HLT_Z0-sig0.120-alpha1_lam16384.0000",all_obs=all_obs,mt1)
# df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha1-E0o2_lam16384.0000", all_obs=all_obs,mt=mt1,df = df1,
#                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE)


tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit,
                 "label"=paste0(df1$label)
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=df$omega  , y=df$Kb,
                       color=paste0("K-",df$label),
                       linetype=paste0("K-",df$label)))
gg<-gg + geom_line(aes(x=df$omega  , y=df$K,
                       color="exact",
                       linetype="exact"))

fig<- myplotly(gg,"","omega", "K", to_print=TRUE )


```




#  Z2 reconstruction

## MG vs NT


```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_2_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,13.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z2-alpha0"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z2-alpha1"
                )
df<-rbind(df,tmp)
##############################
dfY<- get_block_n(Ylog,14.5)
tmp<-data.frame("lam"=dfY[,3]*dfY[,4], "A/A0"=dfY[,9], "B/Bnorm"=dfY[,10], 
                "rho"=dfY[,14],"drho"=dfY[,15], "label"="NT-Z2-alpha2"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_AoverB")
dfY<- get_block_n(mt,1)
dfY<- rbind(dfY, get_block_n(mt,2))
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_output")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z2-sig0.120000-alpha2.00", all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, 
                   ,rename="MG-Z2-alpha0")

df1<-add_corr_to_df(string ="HLT_Z2-sig0.120000-alpha0.00", all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE, rename="MG-Z2-alpha1")


######
################ plot
df1$x<- log2(df1$x)
df1$xfit<- log2(df1$xfit)
df1$tmin<-log2(df1$tmin)
df1$tmax<-log2(df1$tmax)
gg<- plot_df_corr_ggplot(df1)
#gg<-myggplot(fill = FALSE,shape = FALSE)
gg<-gg + geom_point(aes(x=log2(df$lam)  , y=df[,4],
                       color=paste0("rho-",df$label)
                       ))
gg<-gg + geom_errorbar(aes(x=log2(df$lam)  , ymin=df[,4]-df[,5],
                           ymax=df[,4]+df[,5],
                       color=paste0("rho-",df$label)
                       ))



fig<- myplotly(gg,"","log2(lam)", "rho", to_print=TRUE )
#############


tmp<-data.frame("lam"=dfY[,1], "A/A0"=dfY[,2]/dfY[,4], "B/Bnorm"=dfY[,3], "rho"=df1$y,
                "drho"=df1$err,
                  "label"=df1$label
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,2],
                       color=paste0("A/A0-",df$label),
                       linetype=paste0("A/A0-",df$label)))
fig<- myplotly(gg,"","lam", "A/A0", to_print=TRUE ,
               # yrange=c(0,0.0001), xrange=c(-25,0)
               )
################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=log2(df$lam)  , y=df[,3],
                       color=paste0("B/Bnorm-",df$label),
                       linetype=paste0("B/Bnorm-",df$label)))
fig<- myplotly(gg,"","lam", "B/Bnorm", to_print=TRUE,
               # yrange=c(0,20), xrange=c(-25,0) 
               )


```

```{r, echo=FALSE, results='asis', warning=FALSE}

df<-NULL

###################################################### NT

Ylog<-read_df("/home/garofalo/analysis/heavy_quarks/data_htl_format/cB211ab.07.64/t48_64/outputDGammaDq2/DG_2_iset_0_ieps_0_icomb_0.dat")
##############################
dfY<- get_block_n(Ylog,18)
tmp<-data.frame("omega"=dfY[,3], "K"=dfY[,4], "Kb"=dfY[,5],
                 "label"="NT-Z2-alpha1"
                )
df<-rbind(df,tmp)


##############################  MG


###################### MG
mt1<-read_df("/home/garofalo/analysis/heavy_quarks/data_Inc/out/cB211.072.64_ins48_ins64_th6.dat_HLT_kernel")
all_obs<- get_all_corr(mt1)
df1<-add_corr_to_df(string ="HLT_Z2-sig0.120000-alpha0.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = NULL,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z2-sig0.120000-alpha0.00_lam32.0000",
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
df1<-add_corr_to_df(string ="HLT_Z2-sig0.120000-alpha2.00_lam16384.0000",
                    all_obs=all_obs,mt=mt1,df = df1,
                   log = FALSE, number = NULL,nudge = 0,print_res = FALSE)
# res<- get_res(string ="HLT_Z0-sig0.120-alpha1_lam16384.0000",all_obs=all_obs,mt1)
# df1<-add_corr_to_df(string ="HLT_Z0-sig0.120-alpha1-E0o2_lam16384.0000", all_obs=all_obs,mt=mt1,df = df1,
#                    log = FALSE, number = NULL,nudge = 0,print_res = FALSE)


tmp<-data.frame("omega"=df1$x, "K"=df1$y, "Kb"=df1$fit,
                 "label"=paste0(df1$label)
                )
df<-rbind(df,tmp)

################ plot
gg<-myggplot(shape = FALSE,fill = FALSE)
gg<-gg + geom_line(aes(x=df$omega  , y=df$Kb,
                       color=paste0("K-",df$label),
                       linetype=paste0("K-",df$label)))
gg<-gg + geom_line(aes(x=df$omega  , y=df$K,
                       color="exact",
                       linetype="exact"))

fig<- myplotly(gg,"","omega", "K", to_print=TRUE )


```

