#  Overview $d\Gamma/dq^2$


```{r ,include=FALSE}
library(Rose)
library(ggplot2)
library(plotly)
library(knitr)
require(tikzDevice)
df <- data.frame(x = 1:5, y = 1:5)
f1 <- function(df) {
  gg <- ggplot(df, aes(x,y)) + geom_point()
  assign("ggp", plotly::ggplotly(gg), envir=parent.frame())
  #ggp
  df    # NOT returning a plot
}
res1 <- f1(df)
ggp   # Let knit handle the plot
myplotly(ggplot())
```



```{r,results='asis', echo=FALSE}
ens<-c("cB211.072.48","cB211.072.64", "cB211.072.96", "cC211.06.80",
       "cD211.054.96", "cE211.044.112" )
seps<-c("t56_44", "t78_62", "t65_51", "t48_36", "t91_72")
dir<-"/home/garofalo/analysis/heavy_quarks/data_Inc/out/"
ths<- c("1","2","3","4","5","6","7","8","9","9.5")
analysis<-"dGammadq_GEV3_sigma4"
analysis1<-"dGammadq_GEV3_part_sigma4"
len<-0
for (ie in seq_along(ens)){
for (i in seq_along(ths) ){
for (is in seq_along(seps) ){
  name<-paste0(dir,ens[ie],"_th",ths[i],"_",seps[is],".dat_output")
  if(file.exists(name)){
    len<-len+1
  }
}}}

dG<-rep(0, len)
dG_err<-rep(0, len)
q2<-rep(0, len)
ensemble<-rep(0, len)
count<-1
for (ie in seq_along(ens)){
for (i in seq_along(ths) ){
for (is in seq_along(seps) ){
  name<-paste0(dir,ens[ie],"_th",ths[i],"_",seps[is],".dat_output")
  if(file.exists(name)){
    mt<-read_df(name)
    all_obs<- get_all_corr(mt)
    ##############
    if (any(any(all_obs[,2]==analysis))){
      fit<-get_full_res(analysis, all_obs, mt)
      dG[count]<-fit[1,1]
      dG_err[count]<-fit[1,2]
      q2[count]<-fit[1,3]+0.002*ie
      ensemble[count]<-ens[ie]
      count<-count+1
    }
    ##############
    if (any(any(all_obs[,2]==analysis1))){
      fit<-get_full_res(analysis1, all_obs, mt)
      dG[count]<-fit[1,1]
      dG_err[count]<-fit[1,2]
      q2[count]<-fit[1,3]+0.002*ie
      ensemble[count]<-paste0(ens[ie],"part")
      count<-count+1
    }
  }
}}}
gg<- myggplot(fill = FALSE)
gg<- gg + geom_pointrange(aes(x=q2, y=dG,
            ymin=dG-dG_err, ymax=dG+dG_err,
            color=ensemble, shape=ensemble) ,size=1.5, stroke=0.3)

fig<-myplotly(gg,"","$q^2[GeV]$", "$24 \\pi^3 d\\Gamma/dq^2 [GeV^-3]$",to_print = TRUE)
df<-data.frame("ensemble"=ensemble,"q2_GEV"=q2,"dG_GEV1"=dG,"ddG"=dG_err)
```


```{r, eval=FALSE, include=FALSE}
library(ggplot2)
gg<-ggplot()
N<-10
gg<- gg+geom_point(aes(x=c(1:10)/N, y=rep(1,10)),size=4)+theme(aspect.ratio = 0.8,
text = element_text(size=30))
gg<- gg+geom_point(aes(x=(c(1:10)/N)^2, y=rep(1.1,10)), color="red",size=4)+ylim(1,1.5)
gg<- gg+geom_point(aes(x=(c(1,2,3,4,5,6,7,7.8,8,8.5)/N)^2, y=c(1.2)), color="blue",size=4)
gg
```
